export const SET_CITY = "SET_CITY";
export const CLEAR_CITY = "CLEAR_CITY"
export const GET_CITY_BARS = "GET_CITY_BARS";
export const GET_BAR = "GET_BAR"
export const CLEAR_BAR = "CLEAR_BAR"
export const GET_CURRENT_LOCATION = "GET_CURRENT_LOCATION";
export const CLEAR_CURRENT_LOCATION = "CLEAR_CURRENT_LOCATION"


export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const GET_PROFILE = "GET_PROFILE";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const SET_CURRENT_USER = "SET_CURRENT_USER";