export const GET_RESTAURANTS = "GET_RESTAURANTS";

export const GET_CURRENT_LOCATION = "GET_CURRENT_LOCATION";
export const CLEAR_CURRENT_LOCATION = "CLEAR_CURRENT_LOCATION"

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";